# Simple debug
fast_dev_run: true

# Limit time / epochs / steps
max_epochs: 1
min_epochs: 1
max_steps: null
min_steps: null

# use this flag when you need to test something that happens at the end of an epoch
limit_train_batches: 1.0 # Limits the number of train batches in an epoch
limit_val_batches: 1.0
limit_test_batches: 1.0
# similar limit_test_batches, limit_val_batches