tensorboard: 
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: 'tensorboard/' # save the logs here 
  name: 'experiment-name'
  version: 0 # experiment version


wandb: 
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: 'wandb/' # save the data here
  name: 'run-name' # display name for the run
  offline: false # Change to true before submission
  version: 0 # main use to resume previous run
  project: 'comp-name'
